DROP TABLE MDM_PROFESSION_NEW_v2;
CREATE TABLE MDM_PROFESSION_NEW_v3
(
PROF_CLASS_CODE VARCHAR2(20),
PROF_CLASS_DESC_AR VARCHAR2(500),
PROF_CLASS_DESC_EN VARCHAR2(500),
PROF_CLASS_HIER_LEVEL VARCHAR2(20)
);
